/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bulk URL Health Checker API
 * Batch URL health-check submission, background processing, and live progress
 * OpenAPI spec version: 1.0
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customInstance } from '../axios-instance';
export type CreateBatchFromUrlsRequestDto = {
  /** URLs to check, one batch = one BullMQ job per URL */
  urls: string[];
};

export type CreateBatchResponseDto = {
  batchId: string;
  /** Rows that failed URL validation and were skipped (CSV path only) */
  malformedRowCount?: number;
};

export type RequestUrlUploadRequestDto = {
  filename: string;
};

export type RequestUrlUploadResponseDtoUploadFields = { [key: string]: unknown };

export type RequestUrlUploadResponseDto = {
  uploadUrl: string;
  uploadFields: RequestUrlUploadResponseDtoUploadFields;
  objectKey: string;
};

export type CompleteUrlUploadRequestDto = {
  objectKey: string;
};

export type BatchDtoStatus = (typeof BatchDtoStatus)[keyof typeof BatchDtoStatus];

export const BatchDtoStatus = {
  pending: 'pending',
  running: 'running',
  completed: 'completed',
  cancelled: 'cancelled',
} as const;

export type BatchDto = {
  id: string;
  name: string;
  status: BatchDtoStatus;
  totalCount: number;
  succeededCount: number;
  failedCount: number;
  createdAt: string;
  updatedAt: string;
};

export type ListBatchesResponseDto = {
  batches: BatchDto[];
  /** @nullable */
  nextCursor: string | null;
};

export type UrlCheckResultDtoStatus = (typeof UrlCheckResultDtoStatus)[keyof typeof UrlCheckResultDtoStatus];

export const UrlCheckResultDtoStatus = {
  queued: 'queued',
  checking: 'checking',
  succeeded: 'succeeded',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;

export type UrlCheckResultDto = {
  id: string;
  url: string;
  status: UrlCheckResultDtoStatus;
  /** @nullable */
  httpStatusCode: number | null;
  /** @nullable */
  responseTimeMs: number | null;
  /** @nullable */
  pageTitle: string | null;
  /** @nullable */
  errorMessage: string | null;
};

export type PaginatedUrlsResponseDto = {
  urls: UrlCheckResultDto[];
  total: number;
  page: number;
  pageSize: number;
};

export type BatchesControllerListParams = {
  /**
   * Opaque cursor from a previous page's nextCursor
   */
  cursor?: string;
  limit?: number;
};

export type BatchesControllerGetUrlsParams = {
  page?: number;
  pageSize?: number;
};

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const batchesControllerCreateFromUrls = (
  createBatchFromUrlsRequestDto: CreateBatchFromUrlsRequestDto,
  signal?: AbortSignal,
) => {
  return customInstance<CreateBatchResponseDto>({
    url: `/batches`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createBatchFromUrlsRequestDto,
    signal,
  });
};

export const getBatchesControllerCreateFromUrlsMutationKey = () => ['batchesControllerCreateFromUrls'] as const;

export const getBatchesControllerCreateFromUrlsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof batchesControllerCreateFromUrls>>,
    TError,
    BatchesControllerCreateFromUrlsMutationVariables,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof batchesControllerCreateFromUrls>>,
  TError,
  BatchesControllerCreateFromUrlsMutationVariables,
  TContext
> => {
  const mutationKey = getBatchesControllerCreateFromUrlsMutationKey();
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof batchesControllerCreateFromUrls>>,
    BatchesControllerCreateFromUrlsMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return batchesControllerCreateFromUrls(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type BatchesControllerCreateFromUrlsMutationResult = NonNullable<
  Awaited<ReturnType<typeof batchesControllerCreateFromUrls>>
>;
export type BatchesControllerCreateFromUrlsMutationBody = CreateBatchFromUrlsRequestDto;
export type BatchesControllerCreateFromUrlsMutationError = unknown;
export type BatchesControllerCreateFromUrlsMutationVariables = { data: CreateBatchFromUrlsRequestDto };

export const useBatchesControllerCreateFromUrls = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof batchesControllerCreateFromUrls>>,
      TError,
      BatchesControllerCreateFromUrlsMutationVariables,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof batchesControllerCreateFromUrls>>,
  TError,
  BatchesControllerCreateFromUrlsMutationVariables,
  TContext
> => {
  return useMutation(getBatchesControllerCreateFromUrlsMutationOptions(options), queryClient);
};

export const batchesControllerList = (params?: BatchesControllerListParams, signal?: AbortSignal) => {
  return customInstance<ListBatchesResponseDto>({ url: `/batches`, method: 'GET', params, signal });
};

export const getBatchesControllerListInfiniteQueryKey = (params?: BatchesControllerListParams) => {
  return ['infinite', `/batches`, ...(params ? [params] : [])] as const;
};

export const getBatchesControllerListQueryKey = (params?: BatchesControllerListParams) => {
  return [`/batches`, ...(params ? [params] : [])] as const;
};

export const getBatchesControllerListInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof batchesControllerList>>, BatchesControllerListParams['cursor']>,
  TError = unknown,
>(
  params?: BatchesControllerListParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof batchesControllerList>>,
        TError,
        TData,
        QueryKey,
        BatchesControllerListParams['cursor']
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBatchesControllerListInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof batchesControllerList>>,
    QueryKey,
    BatchesControllerListParams['cursor']
  > = ({ signal, pageParam }) => batchesControllerList({ ...params, cursor: pageParam ?? params?.['cursor'] }, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof batchesControllerList>>,
    TError,
    TData,
    QueryKey,
    BatchesControllerListParams['cursor']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BatchesControllerListInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof batchesControllerList>>>;
export type BatchesControllerListInfiniteQueryError = unknown;

export function useBatchesControllerListInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof batchesControllerList>>, BatchesControllerListParams['cursor']>,
  TError = unknown,
>(
  params: undefined | BatchesControllerListParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof batchesControllerList>>,
        TError,
        TData,
        QueryKey,
        BatchesControllerListParams['cursor']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof batchesControllerList>>,
          TError,
          Awaited<ReturnType<typeof batchesControllerList>>,
          QueryKey
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBatchesControllerListInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof batchesControllerList>>, BatchesControllerListParams['cursor']>,
  TError = unknown,
>(
  params?: BatchesControllerListParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof batchesControllerList>>,
        TError,
        TData,
        QueryKey,
        BatchesControllerListParams['cursor']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof batchesControllerList>>,
          TError,
          Awaited<ReturnType<typeof batchesControllerList>>,
          QueryKey
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBatchesControllerListInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof batchesControllerList>>, BatchesControllerListParams['cursor']>,
  TError = unknown,
>(
  params?: BatchesControllerListParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof batchesControllerList>>,
        TError,
        TData,
        QueryKey,
        BatchesControllerListParams['cursor']
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBatchesControllerListInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof batchesControllerList>>, BatchesControllerListParams['cursor']>,
  TError = unknown,
>(
  params?: BatchesControllerListParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof batchesControllerList>>,
        TError,
        TData,
        QueryKey,
        BatchesControllerListParams['cursor']
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBatchesControllerListInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getBatchesControllerListQueryOptions = <
  TData = Awaited<ReturnType<typeof batchesControllerList>>,
  TError = unknown,
>(
  params?: BatchesControllerListParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchesControllerList>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBatchesControllerListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof batchesControllerList>>> = ({ signal }) =>
    batchesControllerList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof batchesControllerList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BatchesControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof batchesControllerList>>>;
export type BatchesControllerListQueryError = unknown;

export function useBatchesControllerList<TData = Awaited<ReturnType<typeof batchesControllerList>>, TError = unknown>(
  params: undefined | BatchesControllerListParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchesControllerList>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof batchesControllerList>>,
          TError,
          Awaited<ReturnType<typeof batchesControllerList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBatchesControllerList<TData = Awaited<ReturnType<typeof batchesControllerList>>, TError = unknown>(
  params?: BatchesControllerListParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchesControllerList>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof batchesControllerList>>,
          TError,
          Awaited<ReturnType<typeof batchesControllerList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBatchesControllerList<TData = Awaited<ReturnType<typeof batchesControllerList>>, TError = unknown>(
  params?: BatchesControllerListParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchesControllerList>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBatchesControllerList<TData = Awaited<ReturnType<typeof batchesControllerList>>, TError = unknown>(
  params?: BatchesControllerListParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchesControllerList>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBatchesControllerListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const batchesControllerRequestUrlUpload = (
  requestUrlUploadRequestDto: RequestUrlUploadRequestDto,
  signal?: AbortSignal,
) => {
  return customInstance<RequestUrlUploadResponseDto>({
    url: `/batches/urls/upload-request`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestUrlUploadRequestDto,
    signal,
  });
};

export const getBatchesControllerRequestUrlUploadMutationKey = () => ['batchesControllerRequestUrlUpload'] as const;

export const getBatchesControllerRequestUrlUploadMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof batchesControllerRequestUrlUpload>>,
    TError,
    BatchesControllerRequestUrlUploadMutationVariables,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof batchesControllerRequestUrlUpload>>,
  TError,
  BatchesControllerRequestUrlUploadMutationVariables,
  TContext
> => {
  const mutationKey = getBatchesControllerRequestUrlUploadMutationKey();
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof batchesControllerRequestUrlUpload>>,
    BatchesControllerRequestUrlUploadMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return batchesControllerRequestUrlUpload(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type BatchesControllerRequestUrlUploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof batchesControllerRequestUrlUpload>>
>;
export type BatchesControllerRequestUrlUploadMutationBody = RequestUrlUploadRequestDto;
export type BatchesControllerRequestUrlUploadMutationError = unknown;
export type BatchesControllerRequestUrlUploadMutationVariables = { data: RequestUrlUploadRequestDto };

export const useBatchesControllerRequestUrlUpload = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof batchesControllerRequestUrlUpload>>,
      TError,
      BatchesControllerRequestUrlUploadMutationVariables,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof batchesControllerRequestUrlUpload>>,
  TError,
  BatchesControllerRequestUrlUploadMutationVariables,
  TContext
> => {
  return useMutation(getBatchesControllerRequestUrlUploadMutationOptions(options), queryClient);
};

export const batchesControllerCompleteUrlUpload = (
  completeUrlUploadRequestDto: CompleteUrlUploadRequestDto,
  signal?: AbortSignal,
) => {
  return customInstance<CreateBatchResponseDto>({
    url: `/batches/urls/complete`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: completeUrlUploadRequestDto,
    signal,
  });
};

export const getBatchesControllerCompleteUrlUploadMutationKey = () => ['batchesControllerCompleteUrlUpload'] as const;

export const getBatchesControllerCompleteUrlUploadMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof batchesControllerCompleteUrlUpload>>,
    TError,
    BatchesControllerCompleteUrlUploadMutationVariables,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof batchesControllerCompleteUrlUpload>>,
  TError,
  BatchesControllerCompleteUrlUploadMutationVariables,
  TContext
> => {
  const mutationKey = getBatchesControllerCompleteUrlUploadMutationKey();
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof batchesControllerCompleteUrlUpload>>,
    BatchesControllerCompleteUrlUploadMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return batchesControllerCompleteUrlUpload(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type BatchesControllerCompleteUrlUploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof batchesControllerCompleteUrlUpload>>
>;
export type BatchesControllerCompleteUrlUploadMutationBody = CompleteUrlUploadRequestDto;
export type BatchesControllerCompleteUrlUploadMutationError = unknown;
export type BatchesControllerCompleteUrlUploadMutationVariables = { data: CompleteUrlUploadRequestDto };

export const useBatchesControllerCompleteUrlUpload = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof batchesControllerCompleteUrlUpload>>,
      TError,
      BatchesControllerCompleteUrlUploadMutationVariables,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof batchesControllerCompleteUrlUpload>>,
  TError,
  BatchesControllerCompleteUrlUploadMutationVariables,
  TContext
> => {
  return useMutation(getBatchesControllerCompleteUrlUploadMutationOptions(options), queryClient);
};

export const batchesControllerGetOne = (batchId: string, signal?: AbortSignal) => {
  return customInstance<BatchDto>({ url: `/batches/${batchId}`, method: 'GET', signal });
};

export const getBatchesControllerGetOneQueryKey = (batchId: string) => {
  return [`/batches/${batchId}`] as const;
};

export const getBatchesControllerGetOneQueryOptions = <
  TData = Awaited<ReturnType<typeof batchesControllerGetOne>>,
  TError = unknown,
>(
  batchId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchesControllerGetOne>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBatchesControllerGetOneQueryKey(batchId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof batchesControllerGetOne>>> = ({ signal }) =>
    batchesControllerGetOne(batchId, signal);

  return { queryKey, queryFn, enabled: batchId !== null && batchId !== undefined, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof batchesControllerGetOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BatchesControllerGetOneQueryResult = NonNullable<Awaited<ReturnType<typeof batchesControllerGetOne>>>;
export type BatchesControllerGetOneQueryError = unknown;

export function useBatchesControllerGetOne<
  TData = Awaited<ReturnType<typeof batchesControllerGetOne>>,
  TError = unknown,
>(
  batchId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchesControllerGetOne>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof batchesControllerGetOne>>,
          TError,
          Awaited<ReturnType<typeof batchesControllerGetOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBatchesControllerGetOne<
  TData = Awaited<ReturnType<typeof batchesControllerGetOne>>,
  TError = unknown,
>(
  batchId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchesControllerGetOne>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof batchesControllerGetOne>>,
          TError,
          Awaited<ReturnType<typeof batchesControllerGetOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBatchesControllerGetOne<
  TData = Awaited<ReturnType<typeof batchesControllerGetOne>>,
  TError = unknown,
>(
  batchId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchesControllerGetOne>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBatchesControllerGetOne<
  TData = Awaited<ReturnType<typeof batchesControllerGetOne>>,
  TError = unknown,
>(
  batchId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchesControllerGetOne>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBatchesControllerGetOneQueryOptions(batchId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const batchesControllerGetUrls = (
  batchId: string,
  params?: BatchesControllerGetUrlsParams,
  signal?: AbortSignal,
) => {
  return customInstance<PaginatedUrlsResponseDto>({ url: `/batches/${batchId}/urls`, method: 'GET', params, signal });
};

export const getBatchesControllerGetUrlsQueryKey = (batchId: string, params?: BatchesControllerGetUrlsParams) => {
  return [`/batches/${batchId}/urls`, ...(params ? [params] : [])] as const;
};

export const getBatchesControllerGetUrlsQueryOptions = <
  TData = Awaited<ReturnType<typeof batchesControllerGetUrls>>,
  TError = unknown,
>(
  batchId: string,
  params?: BatchesControllerGetUrlsParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchesControllerGetUrls>>, TError, TData>> },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBatchesControllerGetUrlsQueryKey(batchId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof batchesControllerGetUrls>>> = ({ signal }) =>
    batchesControllerGetUrls(batchId, params, signal);

  return { queryKey, queryFn, enabled: batchId !== null && batchId !== undefined, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof batchesControllerGetUrls>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BatchesControllerGetUrlsQueryResult = NonNullable<Awaited<ReturnType<typeof batchesControllerGetUrls>>>;
export type BatchesControllerGetUrlsQueryError = unknown;

export function useBatchesControllerGetUrls<
  TData = Awaited<ReturnType<typeof batchesControllerGetUrls>>,
  TError = unknown,
>(
  batchId: string,
  params: undefined | BatchesControllerGetUrlsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchesControllerGetUrls>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof batchesControllerGetUrls>>,
          TError,
          Awaited<ReturnType<typeof batchesControllerGetUrls>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBatchesControllerGetUrls<
  TData = Awaited<ReturnType<typeof batchesControllerGetUrls>>,
  TError = unknown,
>(
  batchId: string,
  params?: BatchesControllerGetUrlsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchesControllerGetUrls>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof batchesControllerGetUrls>>,
          TError,
          Awaited<ReturnType<typeof batchesControllerGetUrls>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBatchesControllerGetUrls<
  TData = Awaited<ReturnType<typeof batchesControllerGetUrls>>,
  TError = unknown,
>(
  batchId: string,
  params?: BatchesControllerGetUrlsParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchesControllerGetUrls>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBatchesControllerGetUrls<
  TData = Awaited<ReturnType<typeof batchesControllerGetUrls>>,
  TError = unknown,
>(
  batchId: string,
  params?: BatchesControllerGetUrlsParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchesControllerGetUrls>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBatchesControllerGetUrlsQueryOptions(batchId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const batchesControllerCancel = (batchId: string, signal?: AbortSignal) => {
  return customInstance<void>({ url: `/batches/${batchId}/cancel`, method: 'POST', signal });
};

export const getBatchesControllerCancelMutationKey = () => ['batchesControllerCancel'] as const;

export const getBatchesControllerCancelMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof batchesControllerCancel>>,
    TError,
    BatchesControllerCancelMutationVariables,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof batchesControllerCancel>>,
  TError,
  BatchesControllerCancelMutationVariables,
  TContext
> => {
  const mutationKey = getBatchesControllerCancelMutationKey();
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof batchesControllerCancel>>,
    BatchesControllerCancelMutationVariables
  > = (props) => {
    const { batchId } = props ?? {};

    return batchesControllerCancel(batchId);
  };

  return { mutationFn, ...mutationOptions };
};

export type BatchesControllerCancelMutationResult = NonNullable<Awaited<ReturnType<typeof batchesControllerCancel>>>;

export type BatchesControllerCancelMutationError = unknown;
export type BatchesControllerCancelMutationVariables = { batchId: string };

export const useBatchesControllerCancel = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof batchesControllerCancel>>,
      TError,
      BatchesControllerCancelMutationVariables,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof batchesControllerCancel>>,
  TError,
  BatchesControllerCancelMutationVariables,
  TContext
> => {
  return useMutation(getBatchesControllerCancelMutationOptions(options), queryClient);
};

export const batchesControllerRetryFailed = (batchId: string, signal?: AbortSignal) => {
  return customInstance<void>({ url: `/batches/${batchId}/retry-failed`, method: 'POST', signal });
};

export const getBatchesControllerRetryFailedMutationKey = () => ['batchesControllerRetryFailed'] as const;

export const getBatchesControllerRetryFailedMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof batchesControllerRetryFailed>>,
    TError,
    BatchesControllerRetryFailedMutationVariables,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof batchesControllerRetryFailed>>,
  TError,
  BatchesControllerRetryFailedMutationVariables,
  TContext
> => {
  const mutationKey = getBatchesControllerRetryFailedMutationKey();
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof batchesControllerRetryFailed>>,
    BatchesControllerRetryFailedMutationVariables
  > = (props) => {
    const { batchId } = props ?? {};

    return batchesControllerRetryFailed(batchId);
  };

  return { mutationFn, ...mutationOptions };
};

export type BatchesControllerRetryFailedMutationResult = NonNullable<
  Awaited<ReturnType<typeof batchesControllerRetryFailed>>
>;

export type BatchesControllerRetryFailedMutationError = unknown;
export type BatchesControllerRetryFailedMutationVariables = { batchId: string };

export const useBatchesControllerRetryFailed = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof batchesControllerRetryFailed>>,
      TError,
      BatchesControllerRetryFailedMutationVariables,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof batchesControllerRetryFailed>>,
  TError,
  BatchesControllerRetryFailedMutationVariables,
  TContext
> => {
  return useMutation(getBatchesControllerRetryFailedMutationOptions(options), queryClient);
};

export const batchEventsControllerEvents = (batchId: string, signal?: AbortSignal) => {
  return customInstance<void>({ url: `/batches/${batchId}/events`, method: 'GET', signal });
};

export const getBatchEventsControllerEventsQueryKey = (batchId: string) => {
  return [`/batches/${batchId}/events`] as const;
};

export const getBatchEventsControllerEventsQueryOptions = <
  TData = Awaited<ReturnType<typeof batchEventsControllerEvents>>,
  TError = unknown,
>(
  batchId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchEventsControllerEvents>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBatchEventsControllerEventsQueryKey(batchId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof batchEventsControllerEvents>>> = ({ signal }) =>
    batchEventsControllerEvents(batchId, signal);

  return { queryKey, queryFn, enabled: batchId !== null && batchId !== undefined, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof batchEventsControllerEvents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BatchEventsControllerEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof batchEventsControllerEvents>>
>;
export type BatchEventsControllerEventsQueryError = unknown;

export function useBatchEventsControllerEvents<
  TData = Awaited<ReturnType<typeof batchEventsControllerEvents>>,
  TError = unknown,
>(
  batchId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchEventsControllerEvents>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof batchEventsControllerEvents>>,
          TError,
          Awaited<ReturnType<typeof batchEventsControllerEvents>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBatchEventsControllerEvents<
  TData = Awaited<ReturnType<typeof batchEventsControllerEvents>>,
  TError = unknown,
>(
  batchId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchEventsControllerEvents>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof batchEventsControllerEvents>>,
          TError,
          Awaited<ReturnType<typeof batchEventsControllerEvents>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBatchEventsControllerEvents<
  TData = Awaited<ReturnType<typeof batchEventsControllerEvents>>,
  TError = unknown,
>(
  batchId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchEventsControllerEvents>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBatchEventsControllerEvents<
  TData = Awaited<ReturnType<typeof batchEventsControllerEvents>>,
  TError = unknown,
>(
  batchId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof batchEventsControllerEvents>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBatchEventsControllerEventsQueryOptions(batchId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
