export const ENV_VARIABLES = {
  PORT: 'PORT',
  DATABASE: {
    HOST: 'DATABASE_HOST',
    PORT: 'DATABASE_PORT',
    USER: 'DATABASE_USER',
    PASSWORD: 'DATABASE_PASSWORD',
    NAME: 'DATABASE_NAME',
  },
  REDIS: {
    HOST: 'REDIS_HOST',
    PORT: 'REDIS_PORT',
  },
  S3: {
    ENDPOINT: 'S3_ENDPOINT',
    PUBLIC_ENDPOINT: 'S3_PUBLIC_ENDPOINT',
    REGION: 'S3_REGION',
    BUCKET_NAME: 'S3_BUCKET_NAME',
    ACCESS_KEY_ID: 'S3_ACCESS_KEY_ID',
    SECRET_ACCESS_KEY: 'S3_SECRET_ACCESS_KEY',
    FORCE_PATH_STYLE: 'S3_FORCE_PATH_STYLE',
  },
} as const;
